import type { Space, RecentSpace, PopularSpace, AdSpace } from '../types/space';

export const savedSpaces: Space[] = [
  {
    id: 1,
    title: '강남역 도보 5분 사무실',
    location: '서울 강남구',
    price: '50,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['주차가능', '24시간', '엘리베이터'],
    isNew: true,
    isFavorite: true,
    floor: '지상 3층',
    area: '66m² (20평)',
  },
  {
    id: 2,
    title: '홍대 창작 스튜디오',
    location: '서울 마포구',
    price: '30,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['방음', '장비대여', '주말가능'],
    isHot: true,
    isFavorite: false,
    floor: '지상 2층',
    area: '50m² (15평)',
  },
  {
    id: 3,
    title: '판교 IT 오피스',
    location: '경기 성남시',
    price: '80,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['고속인터넷', '회의실', '카페'],
    isNew: false,
    isFavorite: true,
    floor: '지상 10층',
    area: '132m² (40평)',
  },
  {
    id: 4,
    title: '이태원 루프탑 카페',
    location: '서울 용산구',
    price: '120,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['루프탑', '뷰맛집', '주차'],
    isHot: true,
    isFavorite: false,
    floor: '지상 5층',
    area: '99m² (30평)',
  },
  {
    id: 5,
    title: '성수동 공유 오피스',
    location: '서울 성동구',
    price: '35,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['공유공간', '네트워킹', '카페'],
    isNew: true,
    isFavorite: true,
    floor: '지상 4층',
    area: '165m² (50평)',
  },
  {
    id: 6,
    title: '부산 해운대 상가',
    location: '부산 해운대구',
    price: '60,000 원/일',
    rating: 4.4,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['해변근처', '유동인구', '주차'],
    isFavorite: false,
    floor: '지상 1층',
    area: '82m² (25평)',
  },
  {
    id: 7,
    title: '대구 동성로 매장',
    location: '대구 중구',
    price: '45,000 원/일',
    rating: 4.3,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['번화가', '지하철', '접근성'],
    isFavorite: true,
    floor: '지하 1층',
    area: '66m² (20평)',
  },
  {
    id: 8,
    title: '인천 송도 창고',
    location: '인천 연수구',
    price: '25,000 원/일',
    rating: 4.2,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['대형공간', '물류', '주차'],
    isFavorite: false,
    floor: '지상 1층',
    area: '330m² (100평)',
  },
  {
    id: 9,
    title: '광주 충장로 스튜디오',
    location: '광주 동구',
    price: '28,000 원/일',
    rating: 4.1,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['촬영', '조명', '장비'],
    isFavorite: true,
    floor: '지상 3층',
    area: '99m² (30평)',
  },
  {
    id: 10,
    title: '대전 둔산동 사무실',
    location: '대전 서구',
    price: '40,000 원/일',
    rating: 4.0,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['정부청사', '교통', '주차'],
    isFavorite: false,
    floor: '지상 7층',
    area: '115m² (35평)',
  },
  {
    id: 11,
    title: '울산 남구 공장',
    location: '울산 남구',
    price: '70,000 원/일',
    rating: 3.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['제조업', '대형', '전력'],
    isFavorite: true,
    floor: '지상 1층',
    area: '495m² (150평)',
  },
  {
    id: 12,
    title: '제주 제주시 카페',
    location: '제주 제주시',
    price: '55,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['관광지', '바다뷰', '힐링'],
    isNew: true,
    isFavorite: false,
    floor: '지상 2층',
    area: '82m² (25평)',
  },
  {
    id: 13,
    title: '수원 영통구 연구소',
    location: '경기 수원시',
    price: '90,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['연구시설', '클린룸', '보안'],
    isFavorite: true,
    floor: '지상 5층',
    area: '231m² (70평)',
  },
  {
    id: 14,
    title: '안양 평촌 학원',
    location: '경기 안양시',
    price: '65,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['교육', '학원가', '접근성'],
    isFavorite: false,
    floor: '지상 8층',
    area: '165m² (50평)',
  },
  {
    id: 15,
    title: '천안 신부동 물류센터',
    location: '충남 천안시',
    price: '85,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['물류', '고속도로', '대형'],
    isFavorite: true,
    floor: '지상 1층',
    area: '661m² (200평)',
  },
  {
    id: 16,
    title: '청주 상당구 공방',
    location: '충북 청주시',
    price: '32,000 원/일',
    rating: 4.4,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['수공예', '체험', '주차'],
    isNew: true,
    isFavorite: false,
    floor: '지상 2층',
    area: '49m² (15평)',
  },
  {
    id: 17,
    title: '전주 완산구 한옥 카페',
    location: '전북 전주시',
    price: '48,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['한옥', '전통', '관광'],
    isHot: true,
    isFavorite: true,
    floor: '지상 1층',
    area: '99m² (30평)',
  },
  {
    id: 18,
    title: '포항 북구 연구실',
    location: '경북 포항시',
    price: '42,000 원/일',
    rating: 4.3,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['연구', '대학가', '실험'],
    isFavorite: false,
    floor: '지상 4층',
    area: '132m² (40평)',
  },
  {
    id: 19,
    title: '창원 의창구 제조업체',
    location: '경남 창원시',
    price: '75,000 원/일',
    rating: 4.2,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['제조', '산업단지', '전력'],
    isFavorite: true,
    floor: '지상 1층',
    area: '826m² (250평)',
  },
  {
    id: 20,
    title: '순천 연향동 갤러리',
    location: '전남 순천시',
    price: '38,000 원/일',
    rating: 4.1,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['전시', '문화', '예술'],
    isFavorite: false,
    floor: '지상 3층',
    area: '66m² (20평)',
  },
  {
    id: 21,
    title: '강릉 교동 펜션',
    location: '강원 강릉시',
    price: '95,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['숙박', '바다', '휴양'],
    isHot: true,
    isFavorite: true,
    floor: '지상 2층',
    area: '198m² (60평)',
  },
  {
    id: 22,
    title: '춘천 퇴계동 음식점',
    location: '강원 춘천시',
    price: '52,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['음식점', '관광지', '주차'],
    isFavorite: false,
    floor: '지상 1층',
    area: '132m² (40평)',
  },
  {
    id: 23,
    title: '원주 단계동 사무실',
    location: '강원 원주시',
    price: '35,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['사무실', '교통', '저렴'],
    isFavorite: true,
    floor: '지상 6층',
    area: '82m² (25평)',
  },
  {
    id: 24,
    title: '속초 조양동 상가',
    location: '강원 속초시',
    price: '68,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['관광', '해변', '상가'],
    isFavorite: false,
    floor: '지상 1층',
    area: '165m² (50평)',
  },
  {
    id: 25,
    title: '태백 황지동 창고',
    location: '강원 태백시',
    price: '22,000 원/일',
    rating: 4.0,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '저렴', '대형'],
    isFavorite: true,
    floor: '지상 1층',
    area: '495m² (150평)',
  },
  {
    id: 26,
    title: '동해 천곡동 공장',
    location: '강원 동해시',
    price: '58,000 원/일',
    rating: 3.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['공장', '항구', '물류'],
    isFavorite: false,
    floor: '지상 1층',
    area: '661m² (200평)',
  },
  {
    id: 27,
    title: '삼척 정상동 펜션',
    location: '강원 삼척시',
    price: '78,000 원/일',
    rating: 4.4,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['펜션', '자연', '힐링'],
    isFavorite: true,
    floor: '지상 2층',
    area: '132m² (40평)',
  },
  {
    id: 28,
    title: '홍천 홍천읍 카페',
    location: '강원 홍천군',
    price: '33,000 원/일',
    rating: 4.3,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['카페', '자연', '조용'],
    isFavorite: false,
    floor: '지상 1층',
    area: '66m² (20평)',
  },
  {
    id: 29,
    title: '횡성 횡성읍 농장',
    location: '강원 횡성군',
    price: '45,000 원/일',
    rating: 4.2,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['농장', '체험', '자연'],
    isFavorite: true,
    floor: '지상 1층',
    area: '991m² (300평)',
  },
  {
    id: 30,
    title: '영월 영월읍 스튜디오',
    location: '강원 영월군',
    price: '29,000 원/일',
    rating: 4.1,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['스튜디오', '조용', '저렴'],
    isFavorite: false,
    floor: '지상 3층',
    area: '49m² (15평)',
  },
  {
    id: 31,
    title: '평창 평창읍 리조트',
    location: '강원 평창군',
    price: '120,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['리조트', '스키', '관광'],
    isHot: true,
    isFavorite: true,
    floor: '지상 5층',
    area: '330m² (100평)',
  },
  {
    id: 32,
    title: '정선 정선읍 민박',
    location: '강원 정선군',
    price: '41,000 원/일',
    rating: 4.0,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['민박', '관광', '전통'],
    isFavorite: false,
    floor: '지상 2층',
    area: '66m² (20평)',
  },
  {
    id: 33,
    title: '철원 갈말읍 농장',
    location: '강원 철원군',
    price: '36,000 원/일',
    rating: 3.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['농장', '넓음', '자연'],
    isFavorite: true,
    floor: '지상 1층',
    area: '1322m² (400평)',
  },
  {
    id: 34,
    title: '화천 화천읍 카페',
    location: '강원 화천군',
    price: '27,000 원/일',
    rating: 4.2,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['카페', '강변', '조용'],
    isFavorite: false,
    floor: '지상 1층',
    area: '49m² (15평)',
  },
  {
    id: 35,
    title: '양구 양구읍 펜션',
    location: '강원 양구군',
    price: '49,000 원/일',
    rating: 4.3,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['펜션', '자연', '휴양'],
    isFavorite: true,
    floor: '지상 2층',
    area: '82m² (25평)',
  },
  {
    id: 36,
    title: '인제 인제읍 글램핑',
    location: '강원 인제군',
    price: '85,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['글램핑', '자연', '캠핑'],
    isNew: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '330m² (100평)',
  },
  {
    id: 37,
    title: '고성 간성읍 펜션',
    location: '강원 고성군',
    price: '72,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['펜션', '해변', '관광'],
    isFavorite: true,
    floor: '지상 3층',
    area: '165m² (50평)',
  },
  {
    id: 38,
    title: '양양 양양읍 서핑샵',
    location: '강원 양양군',
    price: '63,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['서핑', '해변', '레저'],
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '99m² (30평)',
  },
  {
    id: 39,
    title: '서울 종로 한옥 공방',
    location: '서울 종로구',
    price: '95,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['한옥', '전통공예', '체험'],
    isNew: true,
    isFavorite: true,
    floor: '지상 1층',
    area: '66m² (20평)',
  },
  {
    id: 40,
    title: '부천 상동 VR 체험관',
    location: '경기 부천시',
    price: '88,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['VR', '체험', '최신기술'],
    isHot: true,
    isFavorite: false,
    floor: '지상 5층',
    area: '132m² (40평)',
  },
  // 공방 데이터 5곳
  {
    id: 41,
    title: '이태원 도예 공방',
    location: '서울 용산구',
    price: '42,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['도예', '공방', '체험', '주차'],
    isNew: true,
    isFavorite: true,
    floor: '지상 2층',
    area: '50m² (15평)',
  },
  {
    id: 42,
    title: '부산 감천 문화마을 공방',
    location: '부산 사하구',
    price: '35,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['문화마을', '공방', '관광', '예술'],
    isFavorite: false,
    floor: '지상 1층',
    area: '45m² (14평)',
  },
  {
    id: 43,
    title: '경주 황리단길 가죽공방',
    location: '경북 경주시',
    price: '38,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['가죽공예', '공방', '전통', '체험'],
    isFavorite: true,
    floor: '지상 1층',
    area: '55m² (17평)',
  },
  {
    id: 44,
    title: '전주 한옥마을 목공방',
    location: '전북 전주시',
    price: '44,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['목공예', '한옥', '전통', '작업실'],
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '60m² (18평)',
  },
  {
    id: 45,
    title: '제주 애월 유리공방',
    location: '제주 제주시',
    price: '52,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['유리공예', '바다뷰', '공방', '힐링'],
    isNew: true,
    isFavorite: true,
    floor: '지상 2층',
    area: '70m² (21평)',
  },
  // 기존 savedSpaces 배열에 다음 데이터를 추가합니다 (id: 48부터 시작)

  // 창고 데이터 추가 (기존 데이터 외에 추가)
  {
    id: 48,
    title: '김포 물류 대형창고',
    location: '경기 김포시',
    price: '120,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '물류', '대형', '접근성'],
    isNew: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '400m² (121평)',
  },
  {
    id: 49,
    title: '평택항 컨테이너 창고',
    location: '경기 평택시',
    price: '95,000 원/일',
    rating: 4.3,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '항만', '수출입', '컨테이너'],
    isFavorite: true,
    floor: '지상 1층',
    area: '350m² (106평)',
  },
  {
    id: 50,
    title: '용인 냉장 창고',
    location: '경기 용인시',
    price: '150,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '냉장', '식품', '물류'],
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '500m² (151평)',
  },
  {
    id: 51,
    title: '안산 스마트 물류창고',
    location: '경기 안산시',
    price: '180,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '스마트', '자동화', '대형'],
    isFavorite: true,
    floor: '지상 1층',
    area: '600m² (181평)',
  },

  // 상가 데이터 추가 (기존 데이터 외에 추가)
  {
    id: 52,
    title: '명동 중심 상가',
    location: '서울 중구',
    price: '350,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '중심지', '유동인구', '관광'],
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '150m² (45평)',
  },
  {
    id: 53,
    title: '가로수길 프리미엄 상가',
    location: '서울 강남구',
    price: '420,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '프리미엄', '패션', '카페'],
    isFavorite: true,
    floor: '지상 1층',
    area: '180m² (54평)',
  },
  {
    id: 54,
    title: '분당 역세권 상가',
    location: '경기 성남시',
    price: '280,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '역세권', '유동인구', '접근성'],
    isNew: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '120m² (36평)',
  },
  {
    id: 55,
    title: '일산 웨스턴돔 상가',
    location: '경기 고양시',
    price: '230,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '쇼핑몰', '엔터테인먼트', '복합시설'],
    isFavorite: true,
    floor: '지상 1층',
    area: '100m² (30평)',
  },

  // 공방 데이터 추가 (기존 데이터 외에 추가)
  {
    id: 56,
    title: '북촌 전통 도자기 공방',
    location: '서울 종로구',
    price: '65,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['공방', '도자기', '전통', '체험'],
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '70m² (21평)',
  },
  {
    id: 57,
    title: '성수동 가죽 공방',
    location: '서울 성동구',
    price: '58,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['공방', '가죽', '핸드메이드', '워크샵'],
    isNew: true,
    isFavorite: true,
    floor: '지상 2층',
    area: '60m² (18평)',
  },
  {
    id: 58,
    title: '광주 예술 공방',
    location: '광주 동구',
    price: '42,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['공방', '예술', '창작', '전시'],
    isFavorite: false,
    floor: '지상 3층',
    area: '50m² (15평)',
  },
  // 창고 데이터 5개 추가
  {
    id: 59,
    title: '부천 소사 물류창고',
    location: '경기 부천시',
    price: '75,000 원/일',
    rating: 4.3,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '물류', '보관', '트럭접근'],
    isFavorite: true,
    floor: '지상 1층',
    area: '250m² (75평)',
  },
  {
    id: 60,
    title: '시흥 배곧 냉동창고',
    location: '경기 시흥시',
    price: '130,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '냉동', '식품보관', '대형'],
    isNew: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '450m² (136평)',
  },
  {
    id: 61,
    title: '화성 향남 산업창고',
    location: '경기 화성시',
    price: '110,000 원/일',
    rating: 4.4,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '산업', '제조', '전력'],
    isFavorite: true,
    floor: '지상 1층',
    area: '380m² (115평)',
  },
  {
    id: 62,
    title: '광명 소하 보관창고',
    location: '경기 광명시',
    price: '85,000 원/일',
    rating: 4.2,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '보관', '개인창고', '접근성'],
    isFavorite: false,
    floor: '지상 1층',
    area: '280m² (85평)',
  },
  {
    id: 63,
    title: '남양주 다산 물류센터',
    location: '경기 남양주시',
    price: '160,000 원/일',
    rating: 4.7,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '물류센터', '택배', '대형'],
    isHot: true,
    isFavorite: true,
    floor: '지상 1층',
    area: '550m² (166평)',
  },

  // 상가 데이터 3개 추가
  {
    id: 64,
    title: '잠실 롯데월드몰 상가',
    location: '서울 송파구',
    price: '480,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '쇼핑몰', '유동인구', '프리미엄'],
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '200m² (60평)',
  },
  {
    id: 65,
    title: '수원 영통 상업지구 상가',
    location: '경기 수원시',
    price: '190,000 원/일',
    rating: 4.5,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '상업지구', '주거밀집', '주차'],
    isNew: true,
    isFavorite: true,
    floor: '지상 1층',
    area: '90m² (27평)',
  },
  {
    id: 66,
    title: '인천 구월동 로데오거리 상가',
    location: '인천 남동구',
    price: '220,000 원/일',
    rating: 4.6,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '로데오거리', '젊은층', '유흥'],
    isFavorite: false,
    floor: '지상 1층',
    area: '110m² (33평)',
  },
];

// 광고 데이터 별도 관리
export const adSpaces: AdSpace[] = [
  {
    id: 1001,
    title: '강남 프리미엄 비즈니스센터',
    location: '서울 강남구',
    price: '150,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['프리미엄', '비즈니스', '컨시어지', '주차'],
    adType: 'premium',
    adBadge: 'PREMIUM',
    promotionText: '🎯 오픈 기념 첫 달 50% 할인',
    originalPrice: '300,000 원/일',
    isHot: true,
    isFavorite: true,
    floor: '지상 20층',
    area: '330m² (100평)',
  },
  {
    id: 1002,
    title: '판교 테크밸리 스마트오피스',
    location: '경기 성남시',
    price: '200,000 원/일',
    rating: 5.0,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['스마트오피스', 'AI', '최신시설', '네트워킹'],
    adType: 'featured',
    adBadge: 'FEATURED',
    promotionText: '🌟 AI 기반 스마트 시설 완비',
    originalPrice: '250,000 원/일',
    isNew: true,
    isFavorite: false,
    floor: '지상 15층',
    area: '264m² (80평)',
  },
  {
    id: 1003,
    title: '인천 스마트 물류 창고',
    location: '인천 중구',
    price: '280,000 원/일',
    rating: 4.9,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['창고', '스마트물류', '자동화', '대형'],
    adType: 'premium',
    adBadge: 'PREMIUM',
    promotionText: '✨ 최첨단 자동화 시스템 완비',
    originalPrice: '350,000 원/일',
    isNew: true,
    isFavorite: true,
    floor: '지상 3층',
    area: '495m² (150평)',
  },
  {
    id: 1004,
    title: '강남 핵심상권 프리미엄 상가',
    location: '서울 강남구',
    price: '550,000 원/일',
    rating: 5.0,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['상가', '프리미엄', '핵심상권', '대로변'],
    adType: 'featured',
    adBadge: 'FEATURED',
    promotionText: '🌟 계약시 인테리어 지원',
    originalPrice: '650,000 원/일',
    isHot: true,
    isFavorite: false,
    floor: '지상 1층',
    area: '165m² (50평)',
  },
  {
    id: 1005,
    title: '서울숲 아티스트 공방',
    location: '서울 성동구',
    price: '85,000 원/일',
    rating: 4.8,
    image: '/placeholder.svg?height=120&width=120',
    tags: ['공방', '아티스트', '전시', '체험'],
    adType: 'sponsored',
    adBadge: 'AD',
    promotionText: '🎨 예술가를 위한 특별 공간',
    originalPrice: '100,000 원/일',
    isNew: true,
    isFavorite: true,
    floor: '지상 2층',
    area: '66m² (20평)',
  },
];

// recentSpaces 데이터도 업데이트
export const recentSpaces: RecentSpace[] = savedSpaces.slice(5, 13).map((space, index) => ({
  id: space.id,
  name: space.title,
  image: space.image,
  viewedAt: ['2시간 전', '3시간 전', '5시간 전', '1일 전', '1일 전', '2일 전', '3일 전', '1주 전'][index],
  isFavorite: index % 2 === 0, // 예시로 짝수 인덱스만 찜하기 상태 true로 설정
  floor: space.floor || `지상 ${index + 1}층`,
  area: space.area || `${(index + 2) * 33}m² (${Math.floor((index + 2) * 10)}평)`,
}));

// 나머지 코드는 그대로 유지
export const recommendedSpaces: Space[] = savedSpaces.slice(0, 5);

export const popularSpaces: PopularSpace[] = savedSpaces.slice(13, 18).map((space, index) => ({
  rank: index + 1,
  name: space.title,
  views: ['2,456', '1,987', '1,756', '1,432', '1,298'][index],
}));
